#############################################################################
# Makefile for building: WapiDraw
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  WapiDraw.pro
# Template: app
# Command: /home/wapiko/Documents/workspace/C++/qt/5.3/gcc/bin/qmake -o Makefile WapiDraw.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../qt/5.3/gcc/mkspecs/linux-g++ -I. -I../../qt/5.3/gcc/include -I../../qt/5.3/gcc/include/QtWidgets -I../../qt/5.3/gcc/include/QtGui -I../../qt/5.3/gcc/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/wapiko/Documents/workspace/C++/qt/5.3/gcc -Wl,-rpath,/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/lib
LIBS          = $(SUBLIBS) -L/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/wapiko/Documents/workspace/C++/qt/5.3/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		wapidraw.cpp \
		canvas.cpp moc_wapidraw.cpp \
		moc_canvas.cpp
OBJECTS       = main.o \
		wapidraw.o \
		canvas.o \
		moc_wapidraw.o \
		moc_canvas.o
DIST          = ../../qt/5.3/gcc/mkspecs/features/spec_pre.prf \
		../../qt/5.3/gcc/mkspecs/common/shell-unix.conf \
		../../qt/5.3/gcc/mkspecs/common/unix.conf \
		../../qt/5.3/gcc/mkspecs/common/linux.conf \
		../../qt/5.3/gcc/mkspecs/common/gcc-base.conf \
		../../qt/5.3/gcc/mkspecs/common/gcc-base-unix.conf \
		../../qt/5.3/gcc/mkspecs/common/g++-base.conf \
		../../qt/5.3/gcc/mkspecs/common/g++-unix.conf \
		../../qt/5.3/gcc/mkspecs/qconfig.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_core.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_help.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_network.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_script.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../qt/5.3/gcc/mkspecs/features/qt_functions.prf \
		../../qt/5.3/gcc/mkspecs/features/qt_config.prf \
		../../qt/5.3/gcc/mkspecs/linux-g++/qmake.conf \
		../../qt/5.3/gcc/mkspecs/features/spec_post.prf \
		../../qt/5.3/gcc/mkspecs/features/exclusive_builds.prf \
		../../qt/5.3/gcc/mkspecs/features/default_pre.prf \
		../../qt/5.3/gcc/mkspecs/features/resolve_config.prf \
		../../qt/5.3/gcc/mkspecs/features/default_post.prf \
		../../qt/5.3/gcc/mkspecs/features/warn_on.prf \
		../../qt/5.3/gcc/mkspecs/features/qt.prf \
		../../qt/5.3/gcc/mkspecs/features/resources.prf \
		../../qt/5.3/gcc/mkspecs/features/moc.prf \
		../../qt/5.3/gcc/mkspecs/features/unix/opengl.prf \
		../../qt/5.3/gcc/mkspecs/features/uic.prf \
		../../qt/5.3/gcc/mkspecs/features/unix/thread.prf \
		../../qt/5.3/gcc/mkspecs/features/testcase_targets.prf \
		../../qt/5.3/gcc/mkspecs/features/exceptions.prf \
		../../qt/5.3/gcc/mkspecs/features/yacc.prf \
		../../qt/5.3/gcc/mkspecs/features/lex.prf \
		WapiDraw.pro main.cpp \
		wapidraw.cpp \
		canvas.cpp
QMAKE_TARGET  = WapiDraw
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = WapiDraw


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_wapidraw.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: WapiDraw.pro ../../qt/5.3/gcc/mkspecs/linux-g++/qmake.conf ../../qt/5.3/gcc/mkspecs/features/spec_pre.prf \
		../../qt/5.3/gcc/mkspecs/common/shell-unix.conf \
		../../qt/5.3/gcc/mkspecs/common/unix.conf \
		../../qt/5.3/gcc/mkspecs/common/linux.conf \
		../../qt/5.3/gcc/mkspecs/common/gcc-base.conf \
		../../qt/5.3/gcc/mkspecs/common/gcc-base-unix.conf \
		../../qt/5.3/gcc/mkspecs/common/g++-base.conf \
		../../qt/5.3/gcc/mkspecs/common/g++-unix.conf \
		../../qt/5.3/gcc/mkspecs/qconfig.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_core.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_help.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_network.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_script.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../qt/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../qt/5.3/gcc/mkspecs/features/qt_functions.prf \
		../../qt/5.3/gcc/mkspecs/features/qt_config.prf \
		../../qt/5.3/gcc/mkspecs/linux-g++/qmake.conf \
		../../qt/5.3/gcc/mkspecs/features/spec_post.prf \
		../../qt/5.3/gcc/mkspecs/features/exclusive_builds.prf \
		../../qt/5.3/gcc/mkspecs/features/default_pre.prf \
		../../qt/5.3/gcc/mkspecs/features/resolve_config.prf \
		../../qt/5.3/gcc/mkspecs/features/default_post.prf \
		../../qt/5.3/gcc/mkspecs/features/warn_on.prf \
		../../qt/5.3/gcc/mkspecs/features/qt.prf \
		../../qt/5.3/gcc/mkspecs/features/resources.prf \
		../../qt/5.3/gcc/mkspecs/features/moc.prf \
		../../qt/5.3/gcc/mkspecs/features/unix/opengl.prf \
		../../qt/5.3/gcc/mkspecs/features/uic.prf \
		../../qt/5.3/gcc/mkspecs/features/unix/thread.prf \
		../../qt/5.3/gcc/mkspecs/features/testcase_targets.prf \
		../../qt/5.3/gcc/mkspecs/features/exceptions.prf \
		../../qt/5.3/gcc/mkspecs/features/yacc.prf \
		../../qt/5.3/gcc/mkspecs/features/lex.prf \
		WapiDraw.pro \
		/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/lib/libQt5Widgets.prl \
		/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/lib/libQt5Gui.prl \
		/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/lib/libQt5Core.prl
	$(QMAKE) -o Makefile WapiDraw.pro
../../qt/5.3/gcc/mkspecs/features/spec_pre.prf:
../../qt/5.3/gcc/mkspecs/common/shell-unix.conf:
../../qt/5.3/gcc/mkspecs/common/unix.conf:
../../qt/5.3/gcc/mkspecs/common/linux.conf:
../../qt/5.3/gcc/mkspecs/common/gcc-base.conf:
../../qt/5.3/gcc/mkspecs/common/gcc-base-unix.conf:
../../qt/5.3/gcc/mkspecs/common/g++-base.conf:
../../qt/5.3/gcc/mkspecs/common/g++-unix.conf:
../../qt/5.3/gcc/mkspecs/qconfig.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_core.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_designer.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_gui.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_help.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_network.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_qml.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_quick.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_script.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_sql.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_svg.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_xml.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../qt/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../qt/5.3/gcc/mkspecs/features/qt_functions.prf:
../../qt/5.3/gcc/mkspecs/features/qt_config.prf:
../../qt/5.3/gcc/mkspecs/linux-g++/qmake.conf:
../../qt/5.3/gcc/mkspecs/features/spec_post.prf:
../../qt/5.3/gcc/mkspecs/features/exclusive_builds.prf:
../../qt/5.3/gcc/mkspecs/features/default_pre.prf:
../../qt/5.3/gcc/mkspecs/features/resolve_config.prf:
../../qt/5.3/gcc/mkspecs/features/default_post.prf:
../../qt/5.3/gcc/mkspecs/features/warn_on.prf:
../../qt/5.3/gcc/mkspecs/features/qt.prf:
../../qt/5.3/gcc/mkspecs/features/resources.prf:
../../qt/5.3/gcc/mkspecs/features/moc.prf:
../../qt/5.3/gcc/mkspecs/features/unix/opengl.prf:
../../qt/5.3/gcc/mkspecs/features/uic.prf:
../../qt/5.3/gcc/mkspecs/features/unix/thread.prf:
../../qt/5.3/gcc/mkspecs/features/testcase_targets.prf:
../../qt/5.3/gcc/mkspecs/features/exceptions.prf:
../../qt/5.3/gcc/mkspecs/features/yacc.prf:
../../qt/5.3/gcc/mkspecs/features/lex.prf:
WapiDraw.pro:
/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/lib/libQt5Widgets.prl:
/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/lib/libQt5Gui.prl:
/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile WapiDraw.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/WapiDraw1.0.0 || mkdir -p .tmp/WapiDraw1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/WapiDraw1.0.0/ && $(COPY_FILE) --parents wapidraw.h canvas.h .tmp/WapiDraw1.0.0/ && $(COPY_FILE) --parents main.cpp wapidraw.cpp canvas.cpp .tmp/WapiDraw1.0.0/ && $(COPY_FILE) --parents wapidraw.ui .tmp/WapiDraw1.0.0/ && (cd `dirname .tmp/WapiDraw1.0.0` && $(TAR) WapiDraw1.0.0.tar WapiDraw1.0.0 && $(COMPRESS) WapiDraw1.0.0.tar) && $(MOVE) `dirname .tmp/WapiDraw1.0.0`/WapiDraw1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/WapiDraw1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_wapidraw.cpp moc_canvas.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_wapidraw.cpp moc_canvas.cpp
moc_wapidraw.cpp: ../../qt/5.3/gcc/include/QtWidgets/QWidget \
		../../qt/5.3/gcc/include/QtWidgets/qwidget.h \
		../../qt/5.3/gcc/include/QtGui/qwindowdefs.h \
		../../qt/5.3/gcc/include/QtCore/qglobal.h \
		../../qt/5.3/gcc/include/QtCore/qconfig.h \
		../../qt/5.3/gcc/include/QtCore/qfeatures.h \
		../../qt/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../qt/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../qt/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../qt/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../qt/5.3/gcc/include/QtCore/qtypetraits.h \
		../../qt/5.3/gcc/include/QtCore/qsysinfo.h \
		../../qt/5.3/gcc/include/QtCore/qlogging.h \
		../../qt/5.3/gcc/include/QtCore/qflags.h \
		../../qt/5.3/gcc/include/QtCore/qatomic.h \
		../../qt/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../qt/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../qt/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../qt/5.3/gcc/include/QtCore/qmutex.h \
		../../qt/5.3/gcc/include/QtCore/qnumeric.h \
		../../qt/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../qt/5.3/gcc/include/QtCore/qnamespace.h \
		../../qt/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../qt/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		../../qt/5.3/gcc/include/QtCore/qobject.h \
		../../qt/5.3/gcc/include/QtCore/qstring.h \
		../../qt/5.3/gcc/include/QtCore/qchar.h \
		../../qt/5.3/gcc/include/QtCore/qbytearray.h \
		../../qt/5.3/gcc/include/QtCore/qrefcount.h \
		../../qt/5.3/gcc/include/QtCore/qarraydata.h \
		../../qt/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../qt/5.3/gcc/include/QtCore/qlist.h \
		../../qt/5.3/gcc/include/QtCore/qalgorithms.h \
		../../qt/5.3/gcc/include/QtCore/qiterator.h \
		../../qt/5.3/gcc/include/QtCore/qcoreevent.h \
		../../qt/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../qt/5.3/gcc/include/QtCore/qmetatype.h \
		../../qt/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../qt/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../qt/5.3/gcc/include/QtCore/qisenum.h \
		../../qt/5.3/gcc/include/QtCore/qobject_impl.h \
		../../qt/5.3/gcc/include/QtCore/qmargins.h \
		../../qt/5.3/gcc/include/QtGui/qpaintdevice.h \
		../../qt/5.3/gcc/include/QtCore/qrect.h \
		../../qt/5.3/gcc/include/QtCore/qsize.h \
		../../qt/5.3/gcc/include/QtCore/qpoint.h \
		../../qt/5.3/gcc/include/QtGui/qpalette.h \
		../../qt/5.3/gcc/include/QtGui/qcolor.h \
		../../qt/5.3/gcc/include/QtGui/qrgb.h \
		../../qt/5.3/gcc/include/QtCore/qstringlist.h \
		../../qt/5.3/gcc/include/QtCore/qdatastream.h \
		../../qt/5.3/gcc/include/QtCore/qiodevice.h \
		../../qt/5.3/gcc/include/QtCore/qpair.h \
		../../qt/5.3/gcc/include/QtCore/qregexp.h \
		../../qt/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../qt/5.3/gcc/include/QtGui/qbrush.h \
		../../qt/5.3/gcc/include/QtCore/qvector.h \
		../../qt/5.3/gcc/include/QtGui/qmatrix.h \
		../../qt/5.3/gcc/include/QtGui/qpolygon.h \
		../../qt/5.3/gcc/include/QtGui/qregion.h \
		../../qt/5.3/gcc/include/QtCore/qline.h \
		../../qt/5.3/gcc/include/QtGui/qtransform.h \
		../../qt/5.3/gcc/include/QtGui/qpainterpath.h \
		../../qt/5.3/gcc/include/QtGui/qimage.h \
		../../qt/5.3/gcc/include/QtGui/qpixmap.h \
		../../qt/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../qt/5.3/gcc/include/QtCore/qshareddata.h \
		../../qt/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../qt/5.3/gcc/include/QtCore/qhash.h \
		../../qt/5.3/gcc/include/QtGui/qfont.h \
		../../qt/5.3/gcc/include/QtGui/qfontmetrics.h \
		../../qt/5.3/gcc/include/QtGui/qfontinfo.h \
		../../qt/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		../../qt/5.3/gcc/include/QtGui/qcursor.h \
		../../qt/5.3/gcc/include/QtGui/qkeysequence.h \
		../../qt/5.3/gcc/include/QtGui/qevent.h \
		../../qt/5.3/gcc/include/QtCore/qvariant.h \
		../../qt/5.3/gcc/include/QtCore/qmap.h \
		../../qt/5.3/gcc/include/QtCore/qdebug.h \
		../../qt/5.3/gcc/include/QtCore/qtextstream.h \
		../../qt/5.3/gcc/include/QtCore/qlocale.h \
		../../qt/5.3/gcc/include/QtCore/qset.h \
		../../qt/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../qt/5.3/gcc/include/QtCore/qurl.h \
		../../qt/5.3/gcc/include/QtCore/qurlquery.h \
		../../qt/5.3/gcc/include/QtCore/qfile.h \
		../../qt/5.3/gcc/include/QtCore/qfiledevice.h \
		../../qt/5.3/gcc/include/QtGui/qvector2d.h \
		../../qt/5.3/gcc/include/QtGui/qtouchdevice.h \
		../../qt/5.3/gcc/include/QtGui/QPaintEvent \
		../../qt/5.3/gcc/include/QtGui/QPainter \
		../../qt/5.3/gcc/include/QtGui/qpainter.h \
		../../qt/5.3/gcc/include/QtGui/qtextoption.h \
		../../qt/5.3/gcc/include/QtGui/qpen.h \
		../../qt/5.3/gcc/include/QtGui/QMouseEvent \
		../../qt/5.3/gcc/include/QtWidgets/QGridLayout \
		../../qt/5.3/gcc/include/QtWidgets/qgridlayout.h \
		../../qt/5.3/gcc/include/QtWidgets/qlayout.h \
		../../qt/5.3/gcc/include/QtWidgets/qlayoutitem.h \
		../../qt/5.3/gcc/include/QtWidgets/qboxlayout.h \
		../../qt/5.3/gcc/include/QtWidgets/QPushButton \
		../../qt/5.3/gcc/include/QtWidgets/qpushbutton.h \
		../../qt/5.3/gcc/include/QtWidgets/qabstractbutton.h \
		../../qt/5.3/gcc/include/QtGui/qicon.h \
		canvas.h \
		wapidraw.h
	/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/bin/moc $(DEFINES) -I/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/mkspecs/linux-g++ -I/home/wapiko/Documents/workspace/C++/illustsoft/WapiDraw -I/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/include -I/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/include/QtWidgets -I/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/include/QtGui -I/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/include/QtCore wapidraw.h -o moc_wapidraw.cpp

moc_canvas.cpp: ../../qt/5.3/gcc/include/QtWidgets/QWidget \
		../../qt/5.3/gcc/include/QtWidgets/qwidget.h \
		../../qt/5.3/gcc/include/QtGui/qwindowdefs.h \
		../../qt/5.3/gcc/include/QtCore/qglobal.h \
		../../qt/5.3/gcc/include/QtCore/qconfig.h \
		../../qt/5.3/gcc/include/QtCore/qfeatures.h \
		../../qt/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../qt/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../qt/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../qt/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../qt/5.3/gcc/include/QtCore/qtypetraits.h \
		../../qt/5.3/gcc/include/QtCore/qsysinfo.h \
		../../qt/5.3/gcc/include/QtCore/qlogging.h \
		../../qt/5.3/gcc/include/QtCore/qflags.h \
		../../qt/5.3/gcc/include/QtCore/qatomic.h \
		../../qt/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../qt/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../qt/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../qt/5.3/gcc/include/QtCore/qmutex.h \
		../../qt/5.3/gcc/include/QtCore/qnumeric.h \
		../../qt/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../qt/5.3/gcc/include/QtCore/qnamespace.h \
		../../qt/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../qt/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		../../qt/5.3/gcc/include/QtCore/qobject.h \
		../../qt/5.3/gcc/include/QtCore/qstring.h \
		../../qt/5.3/gcc/include/QtCore/qchar.h \
		../../qt/5.3/gcc/include/QtCore/qbytearray.h \
		../../qt/5.3/gcc/include/QtCore/qrefcount.h \
		../../qt/5.3/gcc/include/QtCore/qarraydata.h \
		../../qt/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../qt/5.3/gcc/include/QtCore/qlist.h \
		../../qt/5.3/gcc/include/QtCore/qalgorithms.h \
		../../qt/5.3/gcc/include/QtCore/qiterator.h \
		../../qt/5.3/gcc/include/QtCore/qcoreevent.h \
		../../qt/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../qt/5.3/gcc/include/QtCore/qmetatype.h \
		../../qt/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../qt/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../qt/5.3/gcc/include/QtCore/qisenum.h \
		../../qt/5.3/gcc/include/QtCore/qobject_impl.h \
		../../qt/5.3/gcc/include/QtCore/qmargins.h \
		../../qt/5.3/gcc/include/QtGui/qpaintdevice.h \
		../../qt/5.3/gcc/include/QtCore/qrect.h \
		../../qt/5.3/gcc/include/QtCore/qsize.h \
		../../qt/5.3/gcc/include/QtCore/qpoint.h \
		../../qt/5.3/gcc/include/QtGui/qpalette.h \
		../../qt/5.3/gcc/include/QtGui/qcolor.h \
		../../qt/5.3/gcc/include/QtGui/qrgb.h \
		../../qt/5.3/gcc/include/QtCore/qstringlist.h \
		../../qt/5.3/gcc/include/QtCore/qdatastream.h \
		../../qt/5.3/gcc/include/QtCore/qiodevice.h \
		../../qt/5.3/gcc/include/QtCore/qpair.h \
		../../qt/5.3/gcc/include/QtCore/qregexp.h \
		../../qt/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../qt/5.3/gcc/include/QtGui/qbrush.h \
		../../qt/5.3/gcc/include/QtCore/qvector.h \
		../../qt/5.3/gcc/include/QtGui/qmatrix.h \
		../../qt/5.3/gcc/include/QtGui/qpolygon.h \
		../../qt/5.3/gcc/include/QtGui/qregion.h \
		../../qt/5.3/gcc/include/QtCore/qline.h \
		../../qt/5.3/gcc/include/QtGui/qtransform.h \
		../../qt/5.3/gcc/include/QtGui/qpainterpath.h \
		../../qt/5.3/gcc/include/QtGui/qimage.h \
		../../qt/5.3/gcc/include/QtGui/qpixmap.h \
		../../qt/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../qt/5.3/gcc/include/QtCore/qshareddata.h \
		../../qt/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../qt/5.3/gcc/include/QtCore/qhash.h \
		../../qt/5.3/gcc/include/QtGui/qfont.h \
		../../qt/5.3/gcc/include/QtGui/qfontmetrics.h \
		../../qt/5.3/gcc/include/QtGui/qfontinfo.h \
		../../qt/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		../../qt/5.3/gcc/include/QtGui/qcursor.h \
		../../qt/5.3/gcc/include/QtGui/qkeysequence.h \
		../../qt/5.3/gcc/include/QtGui/qevent.h \
		../../qt/5.3/gcc/include/QtCore/qvariant.h \
		../../qt/5.3/gcc/include/QtCore/qmap.h \
		../../qt/5.3/gcc/include/QtCore/qdebug.h \
		../../qt/5.3/gcc/include/QtCore/qtextstream.h \
		../../qt/5.3/gcc/include/QtCore/qlocale.h \
		../../qt/5.3/gcc/include/QtCore/qset.h \
		../../qt/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../qt/5.3/gcc/include/QtCore/qurl.h \
		../../qt/5.3/gcc/include/QtCore/qurlquery.h \
		../../qt/5.3/gcc/include/QtCore/qfile.h \
		../../qt/5.3/gcc/include/QtCore/qfiledevice.h \
		../../qt/5.3/gcc/include/QtGui/qvector2d.h \
		../../qt/5.3/gcc/include/QtGui/qtouchdevice.h \
		canvas.h
	/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/bin/moc $(DEFINES) -I/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/mkspecs/linux-g++ -I/home/wapiko/Documents/workspace/C++/illustsoft/WapiDraw -I/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/include -I/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/include/QtWidgets -I/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/include/QtGui -I/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/include/QtCore canvas.h -o moc_canvas.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_wapidraw.h
compiler_uic_clean:
	-$(DEL_FILE) ui_wapidraw.h
ui_wapidraw.h: wapidraw.ui
	/home/wapiko/Documents/workspace/C++/qt/5.3/gcc/bin/uic wapidraw.ui -o ui_wapidraw.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp wapidraw.h \
		../../qt/5.3/gcc/include/QtWidgets/QWidget \
		../../qt/5.3/gcc/include/QtWidgets/qwidget.h \
		../../qt/5.3/gcc/include/QtGui/qwindowdefs.h \
		../../qt/5.3/gcc/include/QtCore/qglobal.h \
		../../qt/5.3/gcc/include/QtCore/qconfig.h \
		../../qt/5.3/gcc/include/QtCore/qfeatures.h \
		../../qt/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../qt/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../qt/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../qt/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../qt/5.3/gcc/include/QtCore/qtypetraits.h \
		../../qt/5.3/gcc/include/QtCore/qsysinfo.h \
		../../qt/5.3/gcc/include/QtCore/qlogging.h \
		../../qt/5.3/gcc/include/QtCore/qflags.h \
		../../qt/5.3/gcc/include/QtCore/qatomic.h \
		../../qt/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../qt/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../qt/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../qt/5.3/gcc/include/QtCore/qmutex.h \
		../../qt/5.3/gcc/include/QtCore/qnumeric.h \
		../../qt/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../qt/5.3/gcc/include/QtCore/qnamespace.h \
		../../qt/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../qt/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		../../qt/5.3/gcc/include/QtCore/qobject.h \
		../../qt/5.3/gcc/include/QtCore/qstring.h \
		../../qt/5.3/gcc/include/QtCore/qchar.h \
		../../qt/5.3/gcc/include/QtCore/qbytearray.h \
		../../qt/5.3/gcc/include/QtCore/qrefcount.h \
		../../qt/5.3/gcc/include/QtCore/qarraydata.h \
		../../qt/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../qt/5.3/gcc/include/QtCore/qlist.h \
		../../qt/5.3/gcc/include/QtCore/qalgorithms.h \
		../../qt/5.3/gcc/include/QtCore/qiterator.h \
		../../qt/5.3/gcc/include/QtCore/qcoreevent.h \
		../../qt/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../qt/5.3/gcc/include/QtCore/qmetatype.h \
		../../qt/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../qt/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../qt/5.3/gcc/include/QtCore/qisenum.h \
		../../qt/5.3/gcc/include/QtCore/qobject_impl.h \
		../../qt/5.3/gcc/include/QtCore/qmargins.h \
		../../qt/5.3/gcc/include/QtGui/qpaintdevice.h \
		../../qt/5.3/gcc/include/QtCore/qrect.h \
		../../qt/5.3/gcc/include/QtCore/qsize.h \
		../../qt/5.3/gcc/include/QtCore/qpoint.h \
		../../qt/5.3/gcc/include/QtGui/qpalette.h \
		../../qt/5.3/gcc/include/QtGui/qcolor.h \
		../../qt/5.3/gcc/include/QtGui/qrgb.h \
		../../qt/5.3/gcc/include/QtCore/qstringlist.h \
		../../qt/5.3/gcc/include/QtCore/qdatastream.h \
		../../qt/5.3/gcc/include/QtCore/qiodevice.h \
		../../qt/5.3/gcc/include/QtCore/qpair.h \
		../../qt/5.3/gcc/include/QtCore/qregexp.h \
		../../qt/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../qt/5.3/gcc/include/QtGui/qbrush.h \
		../../qt/5.3/gcc/include/QtCore/qvector.h \
		../../qt/5.3/gcc/include/QtGui/qmatrix.h \
		../../qt/5.3/gcc/include/QtGui/qpolygon.h \
		../../qt/5.3/gcc/include/QtGui/qregion.h \
		../../qt/5.3/gcc/include/QtCore/qline.h \
		../../qt/5.3/gcc/include/QtGui/qtransform.h \
		../../qt/5.3/gcc/include/QtGui/qpainterpath.h \
		../../qt/5.3/gcc/include/QtGui/qimage.h \
		../../qt/5.3/gcc/include/QtGui/qpixmap.h \
		../../qt/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../qt/5.3/gcc/include/QtCore/qshareddata.h \
		../../qt/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../qt/5.3/gcc/include/QtCore/qhash.h \
		../../qt/5.3/gcc/include/QtGui/qfont.h \
		../../qt/5.3/gcc/include/QtGui/qfontmetrics.h \
		../../qt/5.3/gcc/include/QtGui/qfontinfo.h \
		../../qt/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		../../qt/5.3/gcc/include/QtGui/qcursor.h \
		../../qt/5.3/gcc/include/QtGui/qkeysequence.h \
		../../qt/5.3/gcc/include/QtGui/qevent.h \
		../../qt/5.3/gcc/include/QtCore/qvariant.h \
		../../qt/5.3/gcc/include/QtCore/qmap.h \
		../../qt/5.3/gcc/include/QtCore/qdebug.h \
		../../qt/5.3/gcc/include/QtCore/qtextstream.h \
		../../qt/5.3/gcc/include/QtCore/qlocale.h \
		../../qt/5.3/gcc/include/QtCore/qset.h \
		../../qt/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../qt/5.3/gcc/include/QtCore/qurl.h \
		../../qt/5.3/gcc/include/QtCore/qurlquery.h \
		../../qt/5.3/gcc/include/QtCore/qfile.h \
		../../qt/5.3/gcc/include/QtCore/qfiledevice.h \
		../../qt/5.3/gcc/include/QtGui/qvector2d.h \
		../../qt/5.3/gcc/include/QtGui/qtouchdevice.h \
		../../qt/5.3/gcc/include/QtGui/QPaintEvent \
		../../qt/5.3/gcc/include/QtGui/QPainter \
		../../qt/5.3/gcc/include/QtGui/qpainter.h \
		../../qt/5.3/gcc/include/QtGui/qtextoption.h \
		../../qt/5.3/gcc/include/QtGui/qpen.h \
		../../qt/5.3/gcc/include/QtGui/QMouseEvent \
		../../qt/5.3/gcc/include/QtWidgets/QGridLayout \
		../../qt/5.3/gcc/include/QtWidgets/qgridlayout.h \
		../../qt/5.3/gcc/include/QtWidgets/qlayout.h \
		../../qt/5.3/gcc/include/QtWidgets/qlayoutitem.h \
		../../qt/5.3/gcc/include/QtWidgets/qboxlayout.h \
		../../qt/5.3/gcc/include/QtWidgets/QPushButton \
		../../qt/5.3/gcc/include/QtWidgets/qpushbutton.h \
		../../qt/5.3/gcc/include/QtWidgets/qabstractbutton.h \
		../../qt/5.3/gcc/include/QtGui/qicon.h \
		canvas.h \
		../../qt/5.3/gcc/include/QtWidgets/QApplication \
		../../qt/5.3/gcc/include/QtWidgets/qapplication.h \
		../../qt/5.3/gcc/include/QtCore/qcoreapplication.h \
		../../qt/5.3/gcc/include/QtCore/qeventloop.h \
		../../qt/5.3/gcc/include/QtWidgets/qdesktopwidget.h \
		../../qt/5.3/gcc/include/QtGui/qguiapplication.h \
		../../qt/5.3/gcc/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

wapidraw.o: wapidraw.cpp wapidraw.h \
		../../qt/5.3/gcc/include/QtWidgets/QWidget \
		../../qt/5.3/gcc/include/QtWidgets/qwidget.h \
		../../qt/5.3/gcc/include/QtGui/qwindowdefs.h \
		../../qt/5.3/gcc/include/QtCore/qglobal.h \
		../../qt/5.3/gcc/include/QtCore/qconfig.h \
		../../qt/5.3/gcc/include/QtCore/qfeatures.h \
		../../qt/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../qt/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../qt/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../qt/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../qt/5.3/gcc/include/QtCore/qtypetraits.h \
		../../qt/5.3/gcc/include/QtCore/qsysinfo.h \
		../../qt/5.3/gcc/include/QtCore/qlogging.h \
		../../qt/5.3/gcc/include/QtCore/qflags.h \
		../../qt/5.3/gcc/include/QtCore/qatomic.h \
		../../qt/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../qt/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../qt/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../qt/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../qt/5.3/gcc/include/QtCore/qmutex.h \
		../../qt/5.3/gcc/include/QtCore/qnumeric.h \
		../../qt/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../qt/5.3/gcc/include/QtCore/qnamespace.h \
		../../qt/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../qt/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		../../qt/5.3/gcc/include/QtCore/qobject.h \
		../../qt/5.3/gcc/include/QtCore/qstring.h \
		../../qt/5.3/gcc/include/QtCore/qchar.h \
		../../qt/5.3/gcc/include/QtCore/qbytearray.h \
		../../qt/5.3/gcc/include/QtCore/qrefcount.h \
		../../qt/5.3/gcc/include/QtCore/qarraydata.h \
		../../qt/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../qt/5.3/gcc/include/QtCore/qlist.h \
		../../qt/5.3/gcc/include/QtCore/qalgorithms.h \
		../../qt/5.3/gcc/include/QtCore/qiterator.h \
		../../qt/5.3/gcc/include/QtCore/qcoreevent.h \
		../../qt/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../qt/5.3/gcc/include/QtCore/qmetatype.h \
		../../qt/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../qt/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../qt/5.3/gcc/include/QtCore/qisenum.h \
		../../qt/5.3/gcc/include/QtCore/qobject_impl.h \
		../../qt/5.3/gcc/include/QtCore/qmargins.h \
		../../qt/5.3/gcc/include/QtGui/qpaintdevice.h \
		../../qt/5.3/gcc/include/QtCore/qrect.h \
		../../qt/5.3/gcc/include/QtCore/qsize.h \
		../../qt/5.3/gcc/include/QtCore/qpoint.h \
		../../qt/5.3/gcc/include/QtGui/qpalette.h \
		../../qt/5.3/gcc/include/QtGui/qcolor.h \
		../../qt/5.3/gcc/include/QtGui/qrgb.h \
		../../qt/5.3/gcc/include/QtCore/qstringlist.h \
		../../qt/5.3/gcc/include/QtCore/qdatastream.h \
		../../qt/5.3/gcc/include/QtCore/qiodevice.h \
		../../qt/5.3/gcc/include/QtCore/qpair.h \
		../../qt/5.3/gcc/include/QtCore/qregexp.h \
		../../qt/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../qt/5.3/gcc/include/QtGui/qbrush.h \
		../../qt/5.3/gcc/include/QtCore/qvector.h \
		../../qt/5.3/gcc/include/QtGui/qmatrix.h \
		../../qt/5.3/gcc/include/QtGui/qpolygon.h \
		../../qt/5.3/gcc/include/QtGui/qregion.h \
		../../qt/5.3/gcc/include/QtCore/qline.h \
		../../qt/5.3/gcc/include/QtGui/qtransform.h \
		../../qt/5.3/gcc/include/QtGui/qpainterpath.h \
		../../qt/5.3/gcc/include/QtGui/qimage.h \
		../../qt/5.3/gcc/include/QtGui/qpixmap.h \
		../../qt/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../qt/5.3/gcc/include/QtCore/qshareddata.h \
		../../qt/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../qt/5.3/gcc/include/QtCore/qhash.h \
		../../qt/5.3/gcc/include/QtGui/qfont.h \
		../../qt/5.3/gcc/include/QtGui/qfontmetrics.h \
		../../qt/5.3/gcc/include/QtGui/qfontinfo.h \
		../../qt/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		../../qt/5.3/gcc/include/QtGui/qcursor.h \
		../../qt/5.3/gcc/include/QtGui/qkeysequence.h \
		../../qt/5.3/gcc/include/QtGui/qevent.h \
		../../qt/5.3/gcc/include/QtCore/qvariant.h \
		../../qt/5.3/gcc/include/QtCore/qmap.h \
		../../qt/5.3/gcc/include/QtCore/qdebug.h \
		../../qt/5.3/gcc/include/QtCore/qtextstream.h \
		../../qt/5.3/gcc/include/QtCore/qlocale.h \
		../../qt/5.3/gcc/include/QtCore/qset.h \
		../../qt/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../qt/5.3/gcc/include/QtCore/qurl.h \
		../../qt/5.3/gcc/include/QtCore/qurlquery.h \
		../../qt/5.3/gcc/include/QtCore/qfile.h \
		../../qt/5.3/gcc/include/QtCore/qfiledevice.h \
		../../qt/5.3/gcc/include/QtGui/qvector2d.h \
		../../qt/5.3/gcc/include/QtGui/qtouchdevice.h \
		../../qt/5.3/gcc/include/QtGui/QPaintEvent \
		../../qt/5.3/gcc/include/QtGui/QPainter \
		../../qt/5.3/gcc/include/QtGui/qpainter.h \
		../../qt/5.3/gcc/include/QtGui/qtextoption.h \
		../../qt/5.3/gcc/include/QtGui/qpen.h \
		../../qt/5.3/gcc/include/QtGui/QMouseEvent \
		../../qt/5.3/gcc/include/QtWidgets/QGridLayout \
		../../qt/5.3/gcc/include/QtWidgets/qgridlayout.h \
		../../qt/5.3/gcc/include/QtWidgets/qlayout.h \
		../../qt/5.3/gcc/include/QtWidgets/qlayoutitem.h \
		../../qt/5.3/gcc/include/QtWidgets/qboxlayout.h \
		../../qt/5.3/gcc/include/QtWidgets/QPushButton \
		../../qt/5.3/gcc/include/QtWidgets/qpushbutton.h \
		../../qt/5.3/gcc/include/QtWidgets/qabstractbutton.h \
		../../qt/5.3/gcc/include/QtGui/qicon.h \
		canvas.h \
		ui_wapidraw.h \
		../../qt/5.3/gcc/include/QtCore/QVariant \
		../../qt/5.3/gcc/include/QtWidgets/QAction \
		../../qt/5.3/gcc/include/QtWidgets/qaction.h \
		../../qt/5.3/gcc/include/QtWidgets/qactiongroup.h \
		../../qt/5.3/gcc/include/QtWidgets/QApplication \
		../../qt/5.3/gcc/include/QtWidgets/qapplication.h \
		../../qt/5.3/gcc/include/QtCore/qcoreapplication.h \
		../../qt/5.3/gcc/include/QtCore/qeventloop.h \
		../../qt/5.3/gcc/include/QtWidgets/qdesktopwidget.h \
		../../qt/5.3/gcc/include/QtGui/qguiapplication.h \
		../../qt/5.3/gcc/include/QtGui/qinputmethod.h \
		../../qt/5.3/gcc/include/QtWidgets/QButtonGroup \
		../../qt/5.3/gcc/include/QtWidgets/qbuttongroup.h \
		../../qt/5.3/gcc/include/QtWidgets/QHeaderView \
		../../qt/5.3/gcc/include/QtWidgets/qheaderview.h \
		../../qt/5.3/gcc/include/QtWidgets/qabstractitemview.h \
		../../qt/5.3/gcc/include/QtWidgets/qabstractscrollarea.h \
		../../qt/5.3/gcc/include/QtWidgets/qframe.h \
		../../qt/5.3/gcc/include/QtCore/qabstractitemmodel.h \
		../../qt/5.3/gcc/include/QtCore/qitemselectionmodel.h \
		../../qt/5.3/gcc/include/QtWidgets/qabstractitemdelegate.h \
		../../qt/5.3/gcc/include/QtWidgets/qstyleoption.h \
		../../qt/5.3/gcc/include/QtWidgets/qabstractspinbox.h \
		../../qt/5.3/gcc/include/QtGui/qvalidator.h \
		../../qt/5.3/gcc/include/QtCore/qregularexpression.h \
		../../qt/5.3/gcc/include/QtWidgets/qslider.h \
		../../qt/5.3/gcc/include/QtWidgets/qabstractslider.h \
		../../qt/5.3/gcc/include/QtWidgets/qstyle.h \
		../../qt/5.3/gcc/include/QtWidgets/qtabbar.h \
		../../qt/5.3/gcc/include/QtWidgets/qtabwidget.h \
		../../qt/5.3/gcc/include/QtWidgets/qrubberband.h \
		../../qt/5.3/gcc/include/QtWidgets/QMainWindow \
		../../qt/5.3/gcc/include/QtWidgets/qmainwindow.h \
		../../qt/5.3/gcc/include/QtWidgets/QMenuBar \
		../../qt/5.3/gcc/include/QtWidgets/qmenubar.h \
		../../qt/5.3/gcc/include/QtWidgets/qmenu.h \
		../../qt/5.3/gcc/include/QtWidgets/QStatusBar \
		../../qt/5.3/gcc/include/QtWidgets/qstatusbar.h \
		../../qt/5.3/gcc/include/QtWidgets/QToolBar \
		../../qt/5.3/gcc/include/QtWidgets/qtoolbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wapidraw.o wapidraw.cpp

canvas.o: canvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o canvas.o canvas.cpp

moc_wapidraw.o: moc_wapidraw.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wapidraw.o moc_wapidraw.cpp

moc_canvas.o: moc_canvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_canvas.o moc_canvas.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

